#!/usr/bin/env bash
# Make up a story using while + read + IFS

while IFS=: read -r username password uid gid info homedir shell; do
  echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
