#!/usr/bin/env bash
# Display Best School 10 times but on 9th iteration print Hi after Best School
i=1
while [ $i -le 10 ]
do
  echo "Best School"
  if [ $i -eq 9 ]; then
    echo "Hi"
  fi
  i=$((i + 1))
done
