#!/bin/bash
to_decimal() {
  local str="$1"
  local base_chars="$2"
  local len=${#base_chars}
  local result=0 digit idx

  for (( i=0; i<${#str}; i++ )); do
    ch="${str:$i:1}"
    idx=$(expr index "$base_chars" "$ch")
    (( idx-- ))  # 0-based index
    result=$(( result * len + idx ))
  done
  echo "$result"
}

from_decimal() {
  local num="$1"
  local base_chars="$2"
  local len=${#base_chars}
  local result=""

  while (( num > 0 )); do
    rem=$(( num % len ))
    result="${base_chars:rem:1}$result"
    num=$(( num / len ))
  done

  echo "${result:-${base_chars:0:1}}"
}

dec1=$(to_decimal "$WATER" "water")
dec2=$(to_decimal "$STIR" "tir")
sum=$((dec1 + dec2))
from_decimal "$sum" "bestchol"

