#!/usr/bin/env bash
# Create a PID file, print message indefinitely, handle signals accordingly

PIDFILE="/var/run/myscript.pid"

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f "$PIDFILE"; exit 0' SIGQUIT SIGTERM

echo $$ > "$PIDFILE"

while true; do
  echo "To infinity and beyond"
  sleep 2
done
