#!/usr/bin/env bash
# Displays message indefinitely, handles SIGTERM by printing "I am invincible!!!"

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
